# Generated by Django 3.0.6 on 2021-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
    ]
